#pragma once

#include <process.h>



namespace Client
{
	enum LEVEL { 
		LEVEL_STATIC, 
		LEVEL_LOADING,
		LEVEL_LOGO,
		LEVEL_GAMEPLAY,
		LEVEL_STAGE_1,
		LEVEL_CHANGE_STAGE,
		LEVEL_STAGE_2,
		LEVEL_BOSS_1,
		LEVEL_STAGE_3,
		LEVEL_BOSS_2,
		LEVEL_END };

	const unsigned int		g_iWinSizeX = 1280;
	const unsigned int		g_iWinSizeY = 720;

	
	enum NodeStates
	{
		SUCCESS,
		FAILURE,
		RUNNING,
		NONE
	};

	enum Player_Matilda_AnimationType
	{
		Matilda_ANIMATION_HIT = 0,
		Matilda_ANIMATION_DASH,
		Matilda_ANIMATION_SHOT,
		Matilda_ANIMATION_SHOT_CRITICAL,
		Matilda_ANIMATION_ATTACK_SLASH_LEFT,
		Matilda_ANIMATION_ATTACK_SLASH_RIGHT,
		Matilda_ANIMATION_DASH_BACK,
		Matilda_ANIMATION_SLASH_CRITICAL,
		Matilda_ANIMATION_ATTACK_STINGER,
		Matilda_ANIMATION_SLASH_UPPER,
		Matilda_ANIMATION_SHOT_CROUCH,
		Matilda_ANIMATION_ULT_PRE,
		Matilda_ANIMATION_SHOT_CROUCH_READY,
		Matilda_ANIMATION_DASH_SLIDING,
		Matilda_ANIMATION_HIDDEN_MATIDA_A,
		Matilda_ANIMATION_HIDDEN_MATIDA_B,
		Matilda_ANIMATION_HIDDEN_MATIDA_C,
		Matilda_ANIMATION_HIDDEN_MATIDA_D,	
		Matilda_ANIMATION_HIDDEN_MATIDA_E,
		Matilda_ANIMATION_ATTACK_THROWING,
		Matilda_ANIMATION_JUMP_END,
		Matilda_ANIMATION_JUMP_START,
		Matilda_ANIMATION_DASH_BUCK,
		Matilda_ANIMATION_DASH_BUCK_NEXT,
		Matilda_ANIMATION_SLIDING_SHOT,
		Matilda_ANIMATION_HIDDEN_MATIDA_D_SHORT,
		Matilda_ANIMATION_SLASH_SPIN,
		Matilda_ANIMATION_SLASH_SPIN_END,
		Matilda_ANIMATION_NONE,
		Matilda_ANIMATION_SHOT_UPPER_POST,
		Matilda_ANIMATION_SHOT_UPPER_PRE,
		Matilda_ANIMATION_SLASH_STOMP,
		Matilda_ANIMATION_SLASH_CRITICAL_READY,
		Matilda_ANIMATION_SLASH_CRITICAL_GO,
		Matilda_ANIMATION_MOVE_STOP,
		Matilda_ANIMATION_IDLE,
		Matilda_ANIMATION_WALK,
		Matilda_ANIMATION_RUN,
		Matilda_ANIMATION_SHOT_STOP_IDLE,
		Matilda_ANIMATION_SHOT_STOP,
		Matilda_ANIMATION_SLASH_STOP,
		Matilda_ANIMATION_MATILDA_PRE,
		Matilda_ANIMATION_MATILDA,


	};
	enum Player_Amanda_AnimationType
	{
		Amanda_ANIMATION_HIT = 0,
		Amanda_ANIMATION_DASH,
		Amanda_ANIMATION_SHOT,
		Amanda_ANIMATION_SHOT_CRITICAL,
		Amanda_ANIMATION_ATTACK_SLASH_LEFT,
		Amanda_ANIMATION_ATTACK_SLASH_RIGHT,
		Amanda_ANIMATION_DASH_BACK,
		Amanda_ANIMATION_SLASH_CRITICAL,
		Amanda_ANIMATION_ATTACK_STINGER,
		Amanda_ANIMATION_SLASH_UPPER,
		Amanda_ANIMATION_SHOT_CROUCH,
		Amanda_ANIMATION_ULT_PRE,
		Amanda_ANIMATION_SHOT_CROUCH_READY,
		Amanda_ANIMATION_DASH_SLIDING,
		Amanda_ANIMATION_HIDDEN_MATIDA_A,
		Amanda_ANIMATION_HIDDEN_MATIDA_B,
		Amanda_ANIMATION_HIDDEN_MATIDA_C,
		Amanda_ANIMATION_HIDDEN_MATIDA_D,	
		Amanda_ANIMATION_HIDDEN_MATIDA_E,
		Amanda_ANIMATION_JUMP_START,
		Amanda_ANIMATION_JUMP_END,
		Amanda_ANIMATION_ATTACK_THROWING,
		Amanda_ANIMATION_DASH_BUCK,
		Amanda_ANIMATION_DASH_BUCK_NEXT,
		Amanda_ANIMATION_SLIDING_SHOT,
		Amanda_ANIMATION_HIDDEN_AMANDA_D_SHORT,
		Amanda_ANIMATION_SLASH_SPIN,
		Amanda_ANIMATION_SLASH_SPIN_END,
		Amanda_ANIMATION_NONE,
		Amanda_ANIMATION_SHOT_UPPER_PRE,
		Amanda_ANIMATION_SHOT_UPPER_POST,
		Amanda_ANIMATION_SLASH_STOMP,
		Amanda_ANIMATION_SLASH_CRITICAL_GO,
		Amanda_ANIMATION_SLASH_CRITICAL_READY,
		Amanda_ANIMATION_MOVE_STOP,
		Amanda_ANIMATION_IDLE,
		Amanda_ANIMATION_WALK,
		Amanda_ANIMATION_RUN,
		Amanda_ANIMATION_SHOT_STOP_IDLE,
		Amanda_ANIMATION_SHOT_STOP,
		Amanda_ANIMATION_SLASH_STOP,
		Amanda_ANIMATION_MATILDA_PRE,
		Amanda_ANIMATION_MATILDA,


	};



}

extern HINSTANCE g_hInst;
extern HWND g_hWnd;

using namespace Client;
